---
abstract: 'Dancer::Plugin::Queue backend using MongoDB'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Dancer: 0
  Dancer::Plugin::Queue: 0
  Dancer::Test: 0
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  List::Util: 0
  MongoDB: 0.45
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132620'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Queue-MongoDB
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dancer::Plugin::Queue::MongoDB:
    file: lib/Dancer/Plugin/Queue/MongoDB.pm
    version: 0.003
requires:
  Dancer::Plugin::Queue::Role::Queue: 0
  MongoDBx::Queue: 1.000
  Moose: 0
  MooseX::AttributeShortcuts: 0
  namespace::autoclean: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/Dancer-Plugin-Queue-MongoDB/issues
  homepage: https://github.com/dagolden/Dancer-Plugin-Queue-MongoDB
  repository: https://github.com/dagolden/Dancer-Plugin-Queue-MongoDB.git
version: 0.003
x_authority: cpan:DAGOLDEN
